import Head from "next/head";
import Image from "next/image";
import { signIn, signOut, useSession } from "next-auth/client";

export default function Home() {
  const [session, loading] = useSession();
  console.log(session);
  return (
    <div className="flex">
      <Head>
        <title>Chatapp | Stream | Next-Auth</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <div className="">
        {session ? (
          <div>
            <button className="" onClick={() => signOut()}>
              Sign out
            </button>
            <h1>{session?.user.name}</h1>
            <Image src={session?.user.image} width={100} height={100} />
          </div>
        ) : (
          <div>
            <button onClick={() => signIn()}>Sign in</button>
          </div>
        )}
      </div>
    </div>
  );
}
